### ISSUE TITLE
Proje Kısmı ve Todos Hakk.

### ISSUE THREAD

**Issue by ramazansancar** [apo-bozdag/sarisite-pro-extension#9]
Merhaba,
Proje yönetiminin daha rahat, gelişimin daha hızlı olması adına Yapılacaklar listesini Project altına taşımak daha mantıklı olacaktır. Bu sayede takip daha kolay olacak ve topluluk olarak daha hızlı gelişme sağlanacaktır.
https://github.com/apo-bozdag/sarisite-pro-extension/projects

**Comment by apo-bozdag** [comment]
[eklendi](https://github.com/users/apo-bozdag/projects/2/views/1)
